# Generated by Django 5.0.3 on 2024-07-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0002_avaliability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliability',
            name='attended',
        ),
    ]
