# Generated by Django 5.0.3 on 2024-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0007_remove_bookedmeeting_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmeeting',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
