# Generated by Django 5.0.3 on 2024-07-13 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0008_bookedmeeting_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmeeting',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
