# Generated by Django 5.0.3 on 2024-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0009_bookedmeeting_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliability',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
