# Generated by Django 5.0.3 on 2024-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0013_bookedmeeting_is_check_in_bookedmeeting_is_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmeeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedmeeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
