# Generated by Django 5.0.3 on 2024-09-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_calendar', '0014_bookedmeeting_end_time_bookedmeeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedmeeting',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_meeting_availability', to='meeting_calendar.avaliability'),
        ),
    ]
