# Generated by Django 5.0.3 on 2024-07-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_ratings', '0002_offerreviewrating_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferReviewRating',
        ),
    ]
