# Generated by Django 5.0.3 on 2024-04-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsubcategory',
            name='station_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_sub_category', to='stations.stationcategory'),
        ),
    ]
