# Generated by Django 5.0.3 on 2024-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationsubcategory_station_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationcategory',
            old_name='station_category',
            new_name='station',
        ),
    ]
