# Generated by Django 5.0.3 on 2024-04-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_rename_station_category_stationcategory_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationsubcategory',
            old_name='station_sub_category',
            new_name='station_category',
        ),
    ]
