# Generated by Django 5.0.3 on 2024-04-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_rename_station_sub_category_stationsubcategory_station_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecondLevelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first_level_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_level_station', to='stations.firstlevelstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThirdLevelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('second_level_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level_station', to='stations.secondlevelstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
