# Generated by Django 5.0.3 on 2024-04-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_firstlevelstation_secondlevelstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationcategory',
            name='station',
        ),
        migrations.RemoveField(
            model_name='stationsubcategory',
            name='station_category',
        ),
        migrations.CreateModel(
            name='CandidateInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(choices=[('Where are you', 'Location'), ('Who the patient is', 'Patient Info'), ('Other information about the patient', 'Other Patient Info'), ('What you must do', 'Action Required')], max_length=255)),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_station', to='stations.thirdlevelstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='StationCategory',
        ),
        migrations.DeleteModel(
            name='StationSubCategory',
        ),
    ]
