# Generated by Django 5.0.3 on 2024-04-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_remove_stationcategory_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(choices=[('Freely divulged to doctor', 'Freely Divulged'), ('Divulged to doctor if asked', 'Divulged If Asked'), ('Ideas concerns and expectations', 'Ideas Concerns Expectations')], max_length=255)),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_station', to='stations.thirdlevelstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
