# Generated by Django 5.0.3 on 2024-04-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_patientdisclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinstruction',
            name='heading',
            field=models.CharField(choices=[('Where are you', 'Where Are You'), ('Who the patient is', 'Who The Patient Is'), ('Other information about the patient', 'Other Information About The Patient'), ('What you must do', 'What You Must Do')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patientdisclosure',
            name='heading',
            field=models.CharField(choices=[('Freely divulged to doctor', 'Freely Divulged To Doctor'), ('Divulged to doctor if asked', 'Divulged To Doctor If Asked'), ('Ideas concerns and expectations', 'Ideas Concerns And Expectations')], max_length=255),
        ),
        migrations.CreateModel(
            name='ExaminerMarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Data Gathering', 'Data Gathering'), ('Interpersonal skills', 'Interpersonal Skills'), ('Management', 'Management')], max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_mark_sheet', to='stations.thirdlevelstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
