# Generated by Django 5.0.3 on 2024-05-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_stationapproach_stationapproachlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDisclosure',
            new_name='PatientInstruction',
        ),
    ]
