# Generated by Django 5.0.3 on 2024-05-06 07:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_rename_patientdisclosure_patientinstruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateinstruction',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='examinermarksheet',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='examinermarksheetanswer',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='patientinstruction',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='stationapproach',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='stationapproachlink',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='candidateinstruction',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='examinermarksheetanswer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='patientinstruction',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='stationapproach',
            name='learning_points',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
