# Generated by Django 5.0.3 on 2024-05-06 07:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_alter_candidateinstruction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinstruction',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='examinermarksheetanswer',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='patientinstruction',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='stationapproach',
            name='learning_points',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Learning points'),
        ),
    ]
