# Generated by Django 5.0.3 on 2024-05-09 06:47

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_alter_candidateinstruction_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinstruction',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='examinermarksheetanswer',
            name='answer',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='patientinstruction',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='stationapproach',
            name='learning_points',
            field=django_quill.fields.QuillField(),
        ),
    ]
