# Generated by Django 5.0.3 on 2024-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_alter_candidateinstruction_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinstruction',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examinermarksheetanswer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientinstruction',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stationapproach',
            name='learning_points',
            field=models.TextField(),
        ),
    ]
