# Generated by Django 5.0.3 on 2024-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_type', models.CharField(choices=[('Months', 'Months'), ('Days', 'Days'), ('Year', 'Years')], max_length=255)),
                ('duration_period', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
