# Generated by Django 5.0.3 on 2024-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_duration_type_subscriptionproduct_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='currency',
            field=models.CharField(choices=[('usd', 'Usd'), ('gbp', 'Gbp')], default='usd', max_length=10),
            preserve_default=False,
        ),
    ]
