# Generated by Django 5.0.3 on 2024-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionproduct_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='stripe_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
