# Generated by Django 5.0.3 on 2024-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionproduct_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
