# Generated by Django 5.0.3 on 2024-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
