# Generated by Django 5.0.3 on 2024-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_remove_subscriptionproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
