# Generated by Django 5.0.3 on 2024-05-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscriptionproduct_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='currency',
            field=models.CharField(default='gbp', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionproduct',
            name='interval',
            field=models.CharField(choices=[('Month', 'Months'), ('Day', 'Days'), ('Year', 'Years')], max_length=255),
        ),
    ]
