# Generated by Django 5.0.3 on 2024-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, choices=[('successfull', 'Successfull'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
    ]
