# Generated by Django 5.0.3 on 2024-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_successfully',
            field=models.BooleanField(),
        ),
    ]
