# Generated by Django 5.0.3 on 2024-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_alter_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_successfully',
            field=models.BooleanField(blank=True),
        ),
    ]
